name : Postman Collection Workflow
on:
  push:
    branches: [main]
  workflow_dispatch:     
  schedule:
    - cron : 00 04 * * * # 8 am MUT Every Day
    - cron : 30 15 * * * # 730 pm MUT Every DAY
jobs:
    run-postman-tests:
      runs-on: ubuntu-latest

      steps :
        - name : Check out the code
          uses: actions/checkout@v5.0.0
          
        - name : Install nodejs and npm  
          uses: actions/setup-node@v3.9.1
          with:
            node-version: '22'
            
        - name : Install newman and Html-extra globally
          run : |
                npm install -g newman
                npm install -g newman-reporter-htmlextra
        - name : Run the postman collection with newman     
          run : |
                newman run Inwarranty-FlowCollection.postman_collection.json \
                -e QA.postman_environment.json \
                -d testdata.csv \
                -r cli,htmlextra \
                --reporter-htmlextra-export ./newman/index.html
                
        - name : Newman Report
          if: always()
          uses: actions/upload-artifact@v4.6.2
          with :
            name : Newman Report
            path : newman/*.html
            
        - name : Creating Git hub page branch
          if : always ()
          uses : peaceiris/actions-gh-pages@v4.0.0
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: newman
            
        - name : Send email notification
          if : always()
          uses: dawidd6/action-send-mail@v6
          with:
             server_address: smtp.gmail.com
             server_port: 465
             username: ${{ secrets.EMAIL_USERNAME }}
             password: ${{ secrets.EMAIL_PASSWORD }}
             subject: API Test report
             to: yogita.daurby@gmail.xcom
             from: ${{ secrets.EMAIL_USERNAME }}
             body : | 
                    Hi ,the report has beed uploaded and url 
                    is: https://github.com/yogitadaurby-sys/Phoenix-In-warranty-Flow
                  
                   
             
             
          
            
